apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
- name: quay.io/dexidp/dex
  newName: xipcontainerregistrydev.azurecr.io/xip/ip-dex
  newTag: 900678da9c04f55bd59fa38727809b88e5eb65b2